exports["circle.html"] = "<div class=\"circle {done}\"></div>"
exports["countdown.html"] = "<div class=\"countdown\"> <div class=\"num\"></div> {exercise} </div>"
exports["exercise.html"] = "<div class=\"exercise {key}\"> <img src=\"/images/{key}.png\" /> </div>"
exports["progress.html"] = "<div class=\"progress\"> <h1>{title}</h1> <div class=\"all\"> {circles} </div> </div>"
exports["timer.html"] = "<div class=\"timer\"> <div class=\"start\">Press any key to start</div> <div class=\"info\"> <a href=\"http://twitter.com/4zjs\">Made by <span>Azer Koçulu</span></a> </div> {countdown} {progress} </div>"